apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mon-certificate
  namespace: monitoring
spec:
  secretName: mon-tls
  duration: 9125h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
    - arturs k8s
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
  - alexeev.local
  - mon.alexeev.local
  - grafana.alexeev.local
  - prom.alexeev.local
  - netdata.alexeev.local
  ipAddresses:
  - 192.168.0.115
  - 192.168.0.120
  - 192.168.0.121
  issuerRef:
    name: monitoring-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io