---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: videos.courses.rotoro.cloud
spec:
  group: courses.rotoro.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                videoName:
                  type: string
                tags:
                  type: string
                duration:
                  type: integer
  scope: Namespaced
  names:
    plural: videos
    singular: video
    kind: CourseVideo
    shortNames:
      - vid