# Поды - отдельный экземпляр приложения. Самый маленький объект, который можно создать
# в кубере. В поде обычно один контейнер. Не стоит добавлять один под несколько экземпляров
# одного приложения. В одном поде может быть несколько контейнеров, но они не должны быть
# одного типа. Они могут иметь единое пространство для хранения.
# kubectl run nginx --image nginx
# kubectl get pods

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: dev
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: python-container
      image: python
      command: ["python3", "app.py"]
      args: ["--size", "big"]
      env:
        - name: ROCKET_SIZE
          value: average