# Поды - отдельный экземпляр приложения. Самый маленький объект, который можно создать
# в кубере. В поде обычно один контейнер. Не стоит добавлять один под несколько экземпляров
# одного приложения. В одном поде может быть несколько контейнеров, но они не должны быть
# одного типа. Они могут иметь единое пространство для хранения.
# kubectl run nginx --image nginx
# kubectl get pods

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
