apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer
spec:
  selector:
    app: myapp
    type: frontend
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  type: LoadBalancer
  