apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    name: postgres-svc
    app: voting-app
spec:
  selector:
    name: postgres-voting-app
    app: voting-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432