apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
  labels:
    name: voting-app-svc
    app: voting-app
spec:
  selector:
    name: voting-app-pod
    app: voting-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004