# Автоматически создаёт PV

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-gcp-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standart
  replication-type: none