apiVersion: v1
kind: Service
metadata:
  name: jwks-svc
  namespace: namespace-name
  labels:
    app: egress-name
    istio: egress-name
spec:
  ports:
    - name: tcp-14000
      protocol: TCP
      port: 14000
      targetPort: 14000
  selector:
    app: egress-name