apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <html>
    <head>
        <title>Тестовая страница</title>
        <meta charset="UTF-8">
    </head>
    <body>
    <h1>Тестовая страница</h1>
    <p>Простая тестовая страница, версия 3</p>
    </body>
    </html>