apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-voting-app
  labels:
    name: postgres-voting-app
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-voting-app
      app: voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-voting-app
        app: voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust