apiVersion: v1
kind: Service
metadata:
  name: victoriametrics-sys-connect
  namespace: monitoring
  labels:
    app: victoriametrics-sys
spec:
  ports:
  - port: 8428
    name: victoria
    protocol: TCP
  selector:
    app: victoriametrics-sys
    statefulset.kubernetes.io/pod-name: victoriametrics-sys-0