apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: jwks-se
  namespace: namespace-name
  labels:
    app: egress-name
    istio: egress-name
spec:
  exportTo:
    - .
  hosts:
    - jwks.com.ru
  location: MESH_EXTERNAL
  ports:
    - name: http-2000
      number: 2000
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS