apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jwks-vsvc
  namespace: namespace-name
  labels:
    app: egress-name
    istio: egress-name
spec:
  exportTo:
    - .
  gateways:
    - mesh
    - jwks-gw
  hosts:
    - jwks.com.ru
  http:
    - match:
        - gateways:
            - mesh
          port: 2000
      route:
        - destination:
            host: jwks-svc
            port:
              number: 14000
    - match:
        - gateways:
            - jwks-gw
          port: 14000
      route:
        - destination:
            host: jwks.com.ru
            port:
              number: 443