apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: Developer