apiVersion: v1
kind: Pod
metadata:
  name: app-db
  namespace: namespace
  labels:
    app: app07
    function: DD
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: postgres-config